# Generated by Django 3.1.4 on 2020-12-27 17:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=75, verbose_name='title')),
                ('post_content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=200, verbose_name='tags')),
                ('url_text', models.SlugField(max_length=95, unique=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_owner', models.CharField(max_length=35, verbose_name='Yorum sahibi')),
                ('comment_email', models.EmailField(max_length=254, verbose_name="Yorum sahibi'nin mail adresi")),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post', verbose_name='Bağlı olduğu post')),
            ],
        ),
    ]
